# Generated by Django 4.2.4 on 2023-10-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('curso', models.CharField(blank=True, max_length=30, null=True)),
                ('senha', models.CharField(max_length=30)),
                ('tipo_usuario', models.CharField(max_length=30)),
                ('socio', models.BooleanField()),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
    ]
