# Generated by Django 3.1.4 on 2023-12-03 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricaotreino',
            name='PSE_atleta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='PSE_treinador',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='data_treino',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='distancia_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='modelusuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='presenca',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='treino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.treino'),
        ),
        migrations.AlterField(
            model_name='modelusuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
