# Generated by Django 3.1.4 on 2023-11-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_descricaotreino_id_alter_modelusuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricaotreino',
            name='PSE_atleta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='PSE_treinador',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='distancia_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modelusuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
