# Generated by Django 3.1.4 on 2023-11-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231130_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descricaotreino',
            name='PSE_atleta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='PSE_treinador',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='distancia_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='descricaotreino',
            name='presenca',
            field=models.BooleanField(null=True),
        ),
    ]
